// Generated by CoffeeScript 2.6.1
import {
  minify
} from 'html-minifier-terser';

export var INDEX_HTML = 'index.html';

export default {
  name: 'mini_html',
  apply: 'build',
  enforce: 'post',
  generateBundle: async(_, bundle) => {
    var i, ref;
    ref = Object.values(bundle);
    for (i of ref) {
      if (i.type === 'asset' && /\.html?$/.test(i.fileName)) {
        if (INDEX_HTML === i.fileName) {
          i.fileName = INDEX_HTML.slice(0, -1);
        }
        i.source = (await minify(i.source, {
          collapseWhitespace: true,
          html5: true,
          minifyCSS: true,
          minifyJS: true,
          removeAttributeQuotes: true,
          removeComments: true,
          removeRedundantAttributes: true,
          removeScriptTypeAttributes: true,
          removeStyleLinkTypeAttributes: true,
          useShortDoctype: true
        }));
      }
    }
  }
};
